# Generated by Django 5.2.17 on 2026-08-24 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='bots.botinstance')),
                ('cloned_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64)),
                ('type', models.CharField(choices=[('message', 'message'), ('question', 'question'), ('menu', 'menu'), ('condition', 'condition'), ('action', 'action'), ('subscenario', 'subscenario'), ('delay', 'delay')], max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('position', models.JSONField(default=dict)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='scenarios.scenario')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('scenario', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('callback', 'callback'), ('text', 'text'), ('condition', 'condition'), ('always', 'always')], max_length=16)),
                ('trigger_value', models.CharField(blank=True, max_length=255, null=True)),
                ('condition_expr', models.CharField(blank=True, max_length=500, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_out', to='scenarios.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_in', to='scenarios.node')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserSessionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('context_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.botinstance')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scenarios.node')),
            ],
            options={
                'indexes': [models.Index(fields=['bot', 'telegram_user_id', 'created_at'], name='scenarios_u_bot_id_b39418_idx')],
            },
        ),
    ]
